modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
issueTrackerURL="https://github.com/kawaiicakes/Civilization/issues"

[[mods]]
modId="civilization"
version="${file.jarVersion}"
displayName="Civilization"
displayURL="https://github.com/kawaiicakes/Civilization/"
logoFile="civilization.png"
credits="Thanks to ME!"
authors="kawaiicakes"
description='''
This is a template used for my mods so I can just copy paste this for a new 1.19.2 dev environment lol
'''

[[dependencies.civilization]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.civilization]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
