@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.kawaiicakes.civilization.registry.blocks;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;